[package]
name = "web-api"
version = "0.1.0"
edition = "2021"

[dependencies]
twitter-dl = { path = "../twitter-dl" }
aws = { path = "../aws" }
tokio = { version = "1.32", features = ["full"] }
dotenvy = "0.15"
uuid = { version = "1.4", features = [ "v4" ] }
